import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: '#050509',
  },
  splashScreen: {
    flex: 1,
    backgroundColor: '#050509',
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashLogoWrap: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: '#15151d',
    borderWidth: 1,
    borderColor: '#624019',
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashTitle: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '900',
    marginTop: 18,
  },
  splashSub: {
    color: '#d69d44',
    fontWeight: '800',
    marginTop: 5,
    textTransform: 'uppercase',
    fontSize: 12,
  },
  backgroundGlow: {
    position: 'absolute',
    top: -90,
    right: -60,
    width: 190,
    height: 190,
    borderRadius: 95,
    backgroundColor: 'rgba(255,122,8,0.16)',
  },
  appFrame: {
    flex: 1,
    paddingBottom: 152,
  },
  screenContent: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 24,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroTitle: {
    color: '#f8f4ec',
    fontSize: 22,
    fontWeight: '800',
  },
  heroSub: {
    color: '#d69d44',
    marginTop: 4,
    fontSize: 13,
    fontWeight: '600',
  },
  logo: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#15151d',
    borderWidth: 1,
    borderColor: '#624019',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  logoDisc: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 4,
    borderColor: '#ff7a08',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ffc247',
  },
  logoWaveOne: {
    position: 'absolute',
    width: 42,
    height: 10,
    borderRadius: 10,
    backgroundColor: '#00a86b',
    transform: [{rotate: '-24deg'}],
    bottom: 12,
    right: -10,
  },
  logoWaveTwo: {
    position: 'absolute',
    width: 32,
    height: 8,
    borderRadius: 8,
    backgroundColor: '#ffc247',
    transform: [{rotate: '-24deg'}],
    bottom: 21,
    right: -6,
  },
  searchPill: {
    height: 48,
    borderRadius: 12,
    backgroundColor: '#12121a',
    borderWidth: 1,
    borderColor: '#24212a',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginTop: 24,
  },
  searchIcon: {
    color: '#ff7a08',
    fontSize: 20,
    marginRight: 10,
  },
  searchPlaceholder: {
    color: '#c6c0c9',
    fontWeight: '700',
    fontSize: 13,
  },
  homeSearchInput: {
    flex: 1,
    color: '#f5f1ec',
    fontWeight: '700',
    fontSize: 13,
    paddingVertical: 0,
  },
  sectionHeader: {
    marginTop: 24,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: '#f5f1ec',
    fontWeight: '900',
    letterSpacing: 0,
    textTransform: 'uppercase',
    fontSize: 15,
  },
  sectionAction: {
    color: '#ffb11b',
    fontWeight: '800',
    fontSize: 12,
  },
  trendCard: {
    width: 104,
    minHeight: 140,
    borderRadius: 8,
    backgroundColor: '#13131b',
    padding: 9,
    marginRight: 12,
  },
  trendImageWrap: {
    height: 78,
    borderRadius: 6,
    overflow: 'hidden',
  },
  trendImage: {
    borderRadius: 6,
  },
  trendTitle: {
    color: '#ffffff',
    fontWeight: '800',
    marginTop: 9,
    fontSize: 12,
  },
  trendSub: {
    color: '#d69d44',
    fontSize: 10,
    marginTop: 2,
  },
  featuredCard: {
    minHeight: 86,
    borderRadius: 8,
    backgroundColor: '#15151d',
    borderWidth: 1,
    borderColor: '#24212a',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  featuredImageWrap: {
    width: 58,
    height: 58,
  },
  featuredImage: {
    borderRadius: 8,
  },
  featuredText: {
    flex: 1,
    marginLeft: 13,
  },
  kicker: {
    color: '#ffb11b',
    textTransform: 'uppercase',
    fontWeight: '900',
    fontSize: 12,
  },
  featuredTitle: {
    color: '#f3eee7',
    marginTop: 5,
    fontWeight: '700',
  },
  bigPlay: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#ff7a08',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bigPlayIcon: {
    color: '#ffffff',
    fontWeight: '900',
    fontSize: 16,
    marginLeft: 2,
  },
  regionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  regionItem: {
    alignItems: 'center',
    width: 76,
  },
  regionBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 3,
    borderColor: '#f5f1ec',
    backgroundColor: '#111118',
    alignItems: 'center',
    justifyContent: 'center',
  },
  regionFlag: {
    color: '#00a86b',
    fontWeight: '900',
  },
  regionLabel: {
    color: '#97939d',
    marginTop: 8,
    fontSize: 10,
    textAlign: 'center',
  },
  trackRow: {
    minHeight: 70,
    borderRadius: 8,
    backgroundColor: '#14141c',
    borderWidth: 1,
    borderColor: '#23202a',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    marginBottom: 10,
  },
  trackRowActive: {
    borderColor: '#ff7a08',
    backgroundColor: '#1c1718',
  },
  trackCover: {
    width: 48,
    height: 48,
  },
  trackCoverImage: {
    borderRadius: 7,
  },
  trackMeta: {
    flex: 1,
    marginLeft: 12,
  },
  trackTitle: {
    color: '#f5f1ec',
    fontWeight: '800',
    fontSize: 14,
  },
  trackArtist: {
    color: '#9e98a3',
    fontSize: 12,
    marginTop: 3,
  },
  like: {
    color: '#ff7a08',
    fontSize: 22,
  },
  likeButton: {
    width: 34,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 5,
  },
  playButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playIcon: {
    color: '#08080d',
    marginLeft: 2,
    fontWeight: '900',
  },
  pageTitle: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '900',
  },
  sessionCard: {
    marginTop: 22,
    borderRadius: 12,
    backgroundColor: '#2a1a11',
    borderWidth: 1,
    borderColor: '#663b1c',
    padding: 18,
  },
  sessionTitle: {
    color: '#f7d28b',
    fontWeight: '900',
    fontSize: 15,
  },
  sessionText: {
    color: '#d8c8b7',
    lineHeight: 20,
    marginTop: 12,
    fontSize: 13,
  },
  ctaButton: {
    alignSelf: 'flex-start',
    marginTop: 16,
    backgroundColor: '#ff7a08',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  ctaText: {
    color: '#120d09',
    fontWeight: '900',
    textTransform: 'uppercase',
    fontSize: 12,
  },
  genreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  genreTile: {
    width: '48%',
    height: 72,
    borderRadius: 8,
    marginBottom: 12,
    padding: 13,
    overflow: 'hidden',
  },
  genreText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  genreArt: {
    position: 'absolute',
    right: -8,
    bottom: -8,
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  inputWrap: {
    minHeight: 52,
    borderRadius: 12,
    backgroundColor: '#f2f0ed',
    marginTop: 20,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  input: {
    flex: 1,
    color: '#08080d',
    fontWeight: '700',
  },
  emptyText: {
    color: '#a9a4ad',
    marginTop: 30,
    textAlign: 'center',
  },
  libraryHero: {
    height: 120,
    borderRadius: 12,
    marginTop: 20,
    backgroundColor: '#0f5f43',
    alignItems: 'center',
    justifyContent: 'center',
  },
  libraryCount: {
    color: '#ffffff',
    fontSize: 42,
    fontWeight: '900',
  },
  libraryLabel: {
    color: '#d8f4df',
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  localSongsButton: {
    minHeight: 68,
    borderRadius: 8,
    marginTop: 14,
    backgroundColor: '#17131a',
    borderWidth: 1,
    borderColor: '#3d3129',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  localSongsIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#ff7a08',
    color: '#120d09',
    textAlign: 'center',
    lineHeight: 42,
    fontSize: 24,
    fontWeight: '900',
    marginRight: 12,
  },
  localSongsTextBlock: {
    flex: 1,
  },
  localSongsTitle: {
    color: '#f5f1ec',
    fontSize: 15,
    fontWeight: '900',
  },
  localSongsMeta: {
    color: '#b7a696',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  groupToggleButton: {
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: '#241914',
    borderWidth: 1,
    borderColor: '#54351f',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  groupToggleText: {
    color: '#ffb11b',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  groupPanel: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2f2931',
    backgroundColor: '#111118',
    padding: 12,
    marginBottom: 12,
  },
  groupPanelTitle: {
    color: '#f5f1ec',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 10,
    marginTop: 4,
  },
  groupSubTitle: {
    color: '#b7a696',
    fontSize: 12,
    fontWeight: '800',
    marginVertical: 8,
    textTransform: 'uppercase',
  },
  groupSongRow: {
    minHeight: 42,
    borderRadius: 7,
    backgroundColor: '#17131a',
    borderWidth: 1,
    borderColor: '#29232d',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 7,
  },
  groupSongRowActive: {
    borderColor: '#ff7a08',
    backgroundColor: '#21170f',
  },
  groupSongCheck: {
    width: 24,
    color: '#ff7a08',
    fontSize: 18,
    fontWeight: '900',
  },
  groupSongTitle: {
    flex: 1,
    color: '#f5f1ec',
    fontSize: 12,
    fontWeight: '800',
  },
  groupMessage: {
    color: '#ffb11b',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 8,
    marginBottom: 10,
  },
  groupCard: {
    borderRadius: 8,
    backgroundColor: '#17131a',
    borderWidth: 1,
    borderColor: '#2c2630',
    padding: 10,
    marginBottom: 10,
  },
  groupName: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  groupMeta: {
    color: '#a9a4ad',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
    marginBottom: 8,
  },
  groupAddButton: {
    minHeight: 38,
    borderRadius: 19,
    backgroundColor: '#0f5f43',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  groupAddText: {
    color: '#d8f4df',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  groupJoinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  groupCodeInput: {
    flex: 1,
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: '#0b0b10',
    borderWidth: 1,
    borderColor: '#29232d',
    color: '#ffffff',
    paddingHorizontal: 12,
    fontWeight: '800',
  },
  groupJoinButton: {
    minWidth: 78,
    minHeight: 42,
    borderRadius: 21,
    backgroundColor: '#ff7a08',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  groupJoinText: {
    color: '#120d09',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  playlistCard: {
    height: 66,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  playlistCreateCard: {
    minHeight: 56,
    borderRadius: 8,
    backgroundColor: '#111118',
    borderWidth: 1,
    borderColor: '#24212a',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    marginBottom: 12,
  },
  playlistInput: {
    flex: 1,
    color: '#ffffff',
    fontWeight: '700',
    paddingHorizontal: 10,
  },
  playlistCreateButton: {
    minWidth: 78,
    minHeight: 38,
    borderRadius: 19,
    backgroundColor: '#ff7a08',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  playlistCreateText: {
    color: '#120d09',
    fontWeight: '900',
    textTransform: 'uppercase',
    fontSize: 12,
  },
  playlistCover: {
    width: 52,
    height: 52,
    borderRadius: 6,
    marginRight: 12,
  },
  playlistTextBlock: {
    flex: 1,
  },
  profileCard: {
    borderRadius: 12,
    marginTop: 20,
    backgroundColor: '#15151d',
    borderWidth: 1,
    borderColor: '#24212a',
    alignItems: 'center',
    padding: 24,
  },
  profileName: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 14,
  },
  profileMeta: {
    color: '#a9a4ad',
    marginTop: 4,
  },
  authRow: {
    flexDirection: 'row',
    marginTop: 18,
    gap: 10,
  },
  authForm: {
    width: '100%',
    marginTop: 18,
  },
  authSwitch: {
    flexDirection: 'row',
    backgroundColor: '#0f0f16',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2a2530',
    padding: 4,
    marginBottom: 12,
  },
  authSwitchButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authSwitchButtonActive: {
    backgroundColor: '#ff7a08',
  },
  authSwitchText: {
    color: '#b8b0bd',
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  authSwitchTextActive: {
    color: '#120d09',
  },
  authInputWrap: {
    minHeight: 58,
    borderRadius: 8,
    backgroundColor: '#0f0f16',
    borderWidth: 1,
    borderColor: '#2a2530',
    paddingHorizontal: 12,
    paddingTop: 7,
    marginBottom: 10,
  },
  authInputLabel: {
    color: '#d69d44',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  authInput: {
    color: '#ffffff',
    fontWeight: '700',
    paddingVertical: 5,
    fontSize: 14,
  },
  authError: {
    color: '#ff9f85',
    fontWeight: '700',
    marginBottom: 10,
  },
  authPrimaryButton: {
    minWidth: 116,
    borderRadius: 22,
    backgroundColor: '#ff7a08',
    paddingHorizontal: 16,
    paddingVertical: 11,
    alignItems: 'center',
  },
  authSubmitButton: {
    width: '100%',
    minHeight: 46,
    justifyContent: 'center',
    marginTop: 2,
  },
  authButtonDisabled: {
    opacity: 0.62,
  },
  authPrimaryText: {
    color: '#120d09',
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  authSecondaryButton: {
    minWidth: 116,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#ff7a08',
    paddingHorizontal: 16,
    paddingVertical: 11,
    alignItems: 'center',
  },
  authSecondaryText: {
    color: '#ffb11b',
    fontWeight: '900',
    fontSize: 12,
    textTransform: 'uppercase',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  statBox: {
    width: '31%',
    borderRadius: 8,
    backgroundColor: '#111118',
    alignItems: 'center',
    padding: 14,
  },
  statValue: {
    color: '#ffb11b',
    fontWeight: '900',
    fontSize: 22,
  },
  statLabel: {
    color: '#98939e',
    fontSize: 12,
    marginTop: 4,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
  },
  activityDot: {
    color: '#00a86b',
    marginRight: 10,
  },
  activityText: {
    color: '#d7d1da',
    flex: 1,
  },
  player: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 72,
    height: 82,
    borderRadius: 8,
    backgroundColor: '#23212c',
    borderWidth: 1,
    borderColor: '#403845',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 9,
  },
  playerCover: {
    width: 54,
    height: 54,
  },
  playerCoverImage: {
    borderRadius: 6,
  },
  playerMeta: {
    flex: 1,
    marginLeft: 12,
  },
  playerTitle: {
    color: '#ffffff',
    fontWeight: '900',
  },
  playerArtist: {
    color: '#b5adb9',
    marginTop: 3,
    fontSize: 12,
  },
  progressTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: '#4a4652',
    marginTop: 8,
  },
  progressFill: {
    width: '44%',
    height: 3,
    borderRadius: 2,
    backgroundColor: '#00a86b',
  },
  timerRow: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timerText: {
    color: '#98939e',
    fontSize: 10,
    fontWeight: '700',
  },
  playerHeart: {
    color: '#ff7a08',
    fontSize: 22,
    marginHorizontal: 10,
  },
  playerMainButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#ff7a08',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#ffe0b8',
    shadowColor: '#ff7a08',
    shadowOpacity: 0.38,
    shadowRadius: 10,
    elevation: 6,
  },
  playerButtonDisabled: {
    opacity: 0.45,
  },
  playerPauseIcon: {
    width: 20,
    height: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
  },
  playerPauseBar: {
    width: 7,
    borderRadius: 3,
    backgroundColor: '#140d08',
  },
  fullPlayer: {
    flex: 1,
    backgroundColor: '#151315',
  },
  fullPlayerPattern: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: '#1b1719',
    opacity: 0.92,
  },
  fullTopBar: {
    height: 62,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#262126',
    backgroundColor: '#161315',
  },
  fullTopIcon: {
    color: '#d7c7bd',
    fontSize: 26,
    fontWeight: '900',
    width: 34,
    textAlign: 'center',
  },
  fullBrand: {
    color: '#f3b077',
    fontSize: 16,
    fontWeight: '800',
  },
  playerMenu: {
    position: 'absolute',
    top: 58,
    right: 14,
    zIndex: 20,
    width: 230,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#3b302f',
    backgroundColor: '#141217',
    paddingVertical: 6,
    shadowColor: '#000000',
    shadowOpacity: 0.32,
    shadowRadius: 12,
    elevation: 10,
  },
  playerMenuAction: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  playerMenuText: {
    color: '#f5f1ec',
    fontSize: 13,
    fontWeight: '800',
  },
  fullContent: {
    paddingHorizontal: 17,
    paddingTop: 48,
    paddingBottom: 22,
    alignItems: 'center',
  },
  fullCover: {
    width: 252,
    height: 252,
    borderRadius: 126,
    overflow: 'hidden',
    backgroundColor: '#2b2424',
    borderWidth: 8,
    borderColor: '#21191a',
  },
  fullCoverInner: {
    width: '100%',
    height: '100%',
  },
  fullCoverImage: {
    borderRadius: 126,
  },
  fullTitle: {
    color: '#f3ebe6',
    fontSize: 24,
    lineHeight: 29,
    fontWeight: '900',
    marginTop: 36,
    textAlign: 'center',
  },
  fullArtist: {
    color: '#f19a5a',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 8,
    textAlign: 'center',
  },
  visualizer: {
    width: '100%',
    height: 112,
    marginTop: 38,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
  },
  visualizerBar: {
    width: 6,
    borderRadius: 5,
    backgroundColor: '#ff7812',
  },
  fullTimerRow: {
    width: '100%',
    marginTop: 26,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  fullTimerText: {
    color: '#a79b97',
    fontSize: 12,
    fontWeight: '800',
  },
  fullProgressTrack: {
    width: '100%',
    height: 18,
    justifyContent: 'center',
  },
  fullProgressFill: {
    height: 5,
    borderRadius: 5,
    backgroundColor: '#ff7812',
  },
  fullProgressThumb: {
    position: 'absolute',
    width: 13,
    height: 13,
    borderRadius: 7,
    marginLeft: -6,
    backgroundColor: '#ffa15a',
  },
  fullControls: {
    width: '100%',
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  fullIconButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullControlIcon: {
    color: '#ded7d3',
    fontSize: 23,
    fontWeight: '900',
  },
  fullControlActive: {
    color: '#ff7812',
  },
  fullPlayButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#ff7812',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullPlayText: {
    color: '#1c1717',
    fontSize: 32,
    fontWeight: '900',
  },
  fullActionPanel: {
    width: '100%',
    minHeight: 74,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#302832',
    marginTop: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(18,16,20,0.86)',
  },
  fullActionButton: {
    width: '24%',
    minHeight: 66,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullActionIcon: {
    color: '#f1dfd7',
    fontSize: 24,
    fontWeight: '900',
  },
  fullActionActive: {
    color: '#ff7812',
  },
  fullActionText: {
    color: '#b8aaa5',
    marginTop: 5,
    fontSize: 11,
    fontWeight: '800',
  },
  tabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 64,
    backgroundColor: '#101016',
    borderTopWidth: 1,
    borderTopColor: '#23202a',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  tabItem: {
    width: '20%',
    alignItems: 'center',
  },
  tabIcon: {
    color: '#8d8993',
    fontSize: 19,
    fontWeight: '900',
  },
  tabLabel: {
    color: '#8d8993',
    fontSize: 10,
    fontWeight: '800',
    marginTop: 3,
  },
  tabActive: {
    color: '#ff7a08',
  },
});
